import numpy as np
import random
import csv

from Utilities.SafeCastUtil import SafeCastUtil
from ArgumentProcessingService import ArgumentProcessingService


class RandomizedDataGenerator(object):

    GENERATED_DATA_FOLDER = "AutoGeneratedDataFolder"

    FEATURE_PREFIX = "feature"

    CATEGORICAL_SUFFIX = "cat"
    INTEGER_SUFFIX = "int"
    FLOAT_SUFFIX = "float"

    PCT_CATEGORICAL = .3


    @staticmethod
    def generateRandomizedFiles(num_feature_files, num_cells, num_features, is_classifier, monte_carlo_permutations,
                                data_split):

        features_per_file = SafeCastUtil.safeCast(num_features / num_feature_files, int)

        RandomizedDataGenerator.generateFeaturesCSVs(num_feature_files, num_cells, features_per_file)
        RandomizedDataGenerator.generateGeneLists(features_per_file)
        RandomizedDataGenerator.generateResultsCSV(is_classifier, num_cells)
        RandomizedDataGenerator.generateArgsTxt(is_classifier, monte_carlo_permutations, data_split)
        return

    @staticmethod
    def generateFeaturesCSVs(num_feature_files, num_cells, features_per_file):
        features = []

        for feature_file in range(1, num_feature_files + 1):
            for feature in range(1, features_per_file + 1):
                feature_name = RandomizedDataGenerator.FEATURE_PREFIX + SafeCastUtil.safeCast(feature, str)
                features.append(feature_name)

        features_written = 0
        for file_num in range(1, num_feature_files + 1):
            file_name = RandomizedDataGenerator.determineFileName(file_num)

            with open(file_name, 'w') as feature_file:
                writer = csv.writer(feature_file, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
                first_line = []
                for feature_name in range(features_written, features_written + features_per_file):
                    first_line += [features[feature_name]]
                writer.writerow(first_line)

                for cell in range(0, num_cells):
                    line = []
                    for feature_name in range(features_written, features_written + features_per_file):
                        if RandomizedDataGenerator.CATEGORICAL_SUFFIX in file_name:
                            line += [SafeCastUtil.safeCast(np.random.choice(["a", "b", "c", "d", "e"]), str)]
                        elif RandomizedDataGenerator.INTEGER_SUFFIX in file_name:
                            line += [SafeCastUtil.safeCast(np.random.randint(0, 100), str)]
                        else:
                            line += [SafeCastUtil.safeCast(np.random.random_sample(), str)]
                    writer.writerow(line)
                features_written += features_per_file

    @staticmethod
    def determineFileName(file_num):
        file_name = RandomizedDataGenerator.GENERATED_DATA_FOLDER + "/features_" + SafeCastUtil.safeCast(file_num, str)
        rand = np.random.random_sample()
        if rand < RandomizedDataGenerator.PCT_CATEGORICAL:
            file_name += RandomizedDataGenerator.CATEGORICAL_SUFFIX + ".csv"
        elif RandomizedDataGenerator.PCT_CATEGORICAL <= rand < \
                (RandomizedDataGenerator.PCT_CATEGORICAL + (1 - RandomizedDataGenerator.PCT_CATEGORICAL) / 2):
            file_name += RandomizedDataGenerator.INTEGER_SUFFIX + ".csv"
        else:
            file_name += RandomizedDataGenerator.FLOAT_SUFFIX + ".csv"
        return file_name

    @staticmethod
    def generateResultsCSV(is_classifier, num_cells):
        with open(RandomizedDataGenerator.GENERATED_DATA_FOLDER + "/" + ArgumentProcessingService.RESULTS + ".csv",
                  'w') as results_file:
            writer = csv.writer(results_file, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
            writer.writerow(["cell_line_name"] + ["result"])
            for cell in range(0, num_cells):
                cell_name = "cell_line" + SafeCastUtil.safeCast(cell, str)
                if is_classifier:
                    writer.writerow([cell_name, np.random.randint(0, 2)])
                else:
                    writer.writerow([cell_name, np.random.random_sample()])

    @staticmethod
    def generateGeneLists(features_per_file):
        important_features = random.sample(range(1, features_per_file + 1),
                                           SafeCastUtil.safeCast((features_per_file / 3), int))
        gene_list_num = 1
        while len(important_features) > 1:
            gene_list_size = random.randint(2, len(important_features))
            gene_list = [RandomizedDataGenerator.FEATURE_PREFIX + SafeCastUtil.safeCast(feature, str) for feature in
                         important_features[:gene_list_size]]
            important_features = important_features[gene_list_size:]
            file_name = RandomizedDataGenerator.GENERATED_DATA_FOLDER + "/" + ArgumentProcessingService.GENE_LISTS +\
                        SafeCastUtil.safeCast(gene_list_num, str) + ".csv"
            with open(file_name, "w") as file:
                writer = csv.writer(file, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
                writer.writerow(gene_list)
            gene_list_num += 1
        pass

    @staticmethod
    def generateArgsTxt(is_classifier, monte_carlo_permutations=10, data_split=.8):
        file_name = RandomizedDataGenerator.GENERATED_DATA_FOLDER + "/" + ArgumentProcessingService.ARGUMENTS_FILE
        args_file = open(file_name, 'w')
        classifier = '0'
        if is_classifier:
            classifier = '1'
        args_file.write('results=results.csv\n'
                        'is_classifier=' + classifier + "\n"
                        'inner_monte_carlo_permutations=' + SafeCastUtil.safeCast(monte_carlo_permutations, str) + '\n'
                        'outer_monte_carlo_permutations=' + SafeCastUtil.safeCast(monte_carlo_permutations, str) + '\n'
                        'data_split=' + SafeCastUtil.safeCast(data_split, str) + '\n')
        args_file.close()
