class AnalysisType(object):

    FULL_CLA = "FULL_CLA"
    INDIVIDUAL_TRAIN = "INDIVIDUAL_TRAIN"
    FULL_CLA_SPECIFIC_COMBO = "FULL_CLA_SPECIFIC_COMBO"
    NO_GENE_LISTS = "NO_GENE_LISTS"
    RECOMMENDATIONS = "RECOMMENDATIONS"
