class AnalysisType(object):

    FULL_CLA = "FULL_CLA"
    INDIVIDUAL_TRAIN = "INDIVIDUAL_TRAIN"
    FULL_CLA_SPECIFIC_COMBO = "FULL_CLA_SPECIFIC_COMBO"
    SPEARMAN_NO_GENE_LISTS = "SPEARMAN_NO_GENE_LISTS"
